# Robot name goes here
batbat: # change the name
  # default controller
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  # gazebo_ros_control:
  #   pid_gains:
  #     left_rear_wheel_joint:
  #       p: 100.0
  #       i: 0.001
  #       d: 1.0
  #     right_rear_wheel_joint:
  #       p: 1.0
  #       i: 0.001
  #       d: 1.0
  #     left_front_wheel_joint:
  #       p: 0.0
  #       i: 0.001
  #       d: 1.0
  #     right_front_wheel_joint:
  #       p: 0.0
  #       i: 0.001
  #       d: 1.0

  #Controller 1
  rear_motor_left: 
    type: velocity_controllers/JointVelocityController
    joint: left_rear_wheel_joint  
    pid : {p: 70.0 , i: 0.0 , d: 0.0} 
  
  rear_motor_right: 
    type: velocity_controllers/JointVelocityController
    joint: right_rear_wheel_joint
    pid : {p: 70.0 , i: 0.0 , d: 0.0} 
  
  front_motor_left: 
    type: effort_controllers/JointPositionController 
    joint: left_front_wheel_joint  
    pid : {p: 70.0 , i: 0.0 , d: 0.0} 

  front_motor_right: 
    type: effort_controllers/JointPositionController 
    joint: right_front_wheel_joint  
    pid : {p: 70.0 , i: 0.0 , d: 0.0} 

  


  

  # Controller 2
  # Controller 3
  # ....
  # Controller n


 